main: "net.defracted.adminutils.Main"
version: "1.1.0"
name: "AdminUtils"
author: "Defracted7"
api-version: "1.15"


commands:
  adminutils:
    description: "Управление плагином"
    usage: "/adminutils [reload]"
    permission: "adminutils.manage"

  ban:
    description: "Банит игроков"
    usage: "/ban <игрок> <срок в минутах> <причина>"
    permission: "adminutils.ban"

  mute:
    description: "Выдаёт муты"
    usage: "/mute <игрок> <срок в минутах> <причина>"
    permission: "adminutils.mute"

  unmute:
    description: "Снимает муты"
    usage: "/unmute <игрок>"
    permission: "adminutils.mute"

  heal:
    description: "Лечит игрока"
    usage: "/heal [игрок]"
    permission: "adminutils.heal"

  god:
    description: "Включает неуюзвимость"
    usage: "/god <игрок>"
    permission: "adminutils.god"

  fly:
    description: "Включает режим полёта"
    usage: "/fly [игрок]"
    permission: "adminutils.fly"

  ping:
    description: "Проверяет задержку"
    usage: "/ping"

  back:
    description: "Возвращает на место смерти"
    usage: "/back"
    permission: "adminutils.back"

# Права

permissions:
  adminutils.manage:
    description: "Возможность использовать /adminutils"
    default: op

  adminutils.ban:
    description: "Возможность использовать /ban"
    default: op

  adminutils.mute:
    description: "Возможность использовать /mute и /unmute"
    default: op

  adminutils.mute.bypass:
    description: "Иммунитет к мутам"
    default: false

  adminutils.heal:
    description: "Возможность использовать /heal"
    default: op

  adminutils.heal.others:
    description: "Возможность использовать /heal на других игроках"
    default: op

  adminutils.god:
    description: "Возможность использовать /god"
    default: op

  adminutils.god.others:
    description: "Возможность использовать /god на других игроках"
    default: op

  adminutils.fly:
    description: "Возможность использовать /fly"
    default: op

  adminutils.fly.others:
    description: "Возможность использовать /fly на других игроках"
    default: op

  adminutils.back:
    description: "Доступ к команде /back"
    default: op

  adminutils.colored_chat:
    description: "Даёт доступ к цветным сообщениям"
    default: false

  # Префиксы, на случай отсутствия LuckPerms

  adminutils.prefix.senior:
    description: "Префикс старшего модератора"
    default: false

  adminutils.prefix.mod:
    description: "Префикс модератора"
    default: false

  adminutils.prefix.helper:
    description: "Префикс хэлпера"
    default: false

  adminutils.*:
    description: "Полный доступ ко всем командам плагина AdminUtils"
    default: false
    children:
      adminutils.manage: true
      adminutils.ban: true
      adminutils.mute: true
      adminutils.mute.bypass: true
      adminutils.heal: true
      adminutils.heal.others: true
      adminutils.god: true
      adminutils.god.others: true
      adminutils.fly: true
      adminutils.fly.others: true
      adminutils.back: true
      adminutils.colored_chat: true