main: "net.defracted.adminutils.Main"
version: "1.0.7"
name: "AdminUtils"
author: "Defracted7"
api-version: "1.15"


commands:
  adminutils:
    description: "Управление плагином"
    usage: "/adminutils [reload]"
    permission: "adminutils.manage"

  ban:
    description: "Банит игроков"
    usage: "/ban <игрок> <срок в минутах> <причина>"
    permission: "adminutils.ban"

  heal:
    description: "Лечит игрока"
    usage: "/heal <игрок>"
    permission: "adminutils.heal"

  god:
    description: "Включает неуюзвимость"
    usage: "/god <игрок>"
    permission: "adminutils.god"

  ping:
    description: "Проверяет задержку"
    usage: "/ping"

  back:
    description: "Возвращает на место смерти"
    usage: "/back"
    permission: "adminutils.back"

permissions:
  adminutils.manage:
    description: "Доступ к команде /adminutils"
    default: op

  adminutils.ban:
    description: "Доступ к команде /ban"
    default: op

  adminutils.heal:
    description: "Доступ к команде /heal"
    default: op

  adminutil.back:
    description: "Доступ к команде /back"
    default: op

  adminutils.colored_chat:
    description: "Даёт доступ к цветным сообщениям"
    default: false

  # Префиксы, на случай отсутствия LuckPerms

  adminutils.prefix.senior:
    description: "Префикс старшего модератора"
    default: false

  adminutils.prefix.mod:
    description: "Префикс модератора"
    default: false

  adminutils.prefix.helper:
    description: "Префикс хэлпера"
    default: false

  adminutils.*:
    description: "Полный доступ ко всем командам плагина AdminUtils"
    children:
      adminutils.manage: true
      adminutils.ban: true
      adminutils.heal: true
      adminutils.god: true
      adminutils.back: true
      adminutils.colored_chat: true