main: "net.Defracted.AdminUtils.Main"
version: "1.0.6"
name: "AdminUtils"
author: "Defracted7"
api-version: "1.15"


commands:
  adminutils:
    description: "Управление плагином"
    usage: "/adminutils [reload]"
    permission: "adminutils.manage"

  ban:
    description: "Банит игроков"
    usage: "/ban <игрок> <срок в минутах> <причина>"
    permission: "adminutils.ban"

  heal:
    description: "Лечит игрока"
    usage: "/heal <игрок>"
    permission: "adminutils.heal"

  god:
    description: "Включает неуюзвимость"
    usage: "/god <игрок>"
    permission: "adminutils.god"


permissions:
  adminutils.manage:
    description: "Доступ к команде /adminutils"
    default: op

  adminutils.ban:
    description: "Доступ к команде /ban"
    default: op

  adminutils.heal:
    description: "Доступ к команде /heal"
    default: op

  adminutil.god:
    description: "Доступ к команде /god"
    default: op

  adminutils.*:
    description: "Полный доступ ко всем командам плагина AdminUtils"
    children:
      adminutils.manage: true
      adminutils.ban: true
      adminutils.heal: true
      adminutils.god: true
