main: "net.Defracted.AdminUtils.Main"
version: "1.0"
name: "AdminUtils"
author: "Defracted7"
api-version: "1.15"

commands:
  heal:
    description: "Лечит игрока"
    usage: "/heal <игрок>"
    permission: "adminutils.heal"
  god:
    description: "Включает неуюзвимость"
    usage: "/god <игрок>"
    permission: "adminutils.god"

permissions:
  adminutils.heal:
    description: "Доступ к команде /heal"
    default: op

  adminutil.god:
    description: "Доступ к команде /god"
    default: op

  adminutils.*:
    description: "Полный доступ ко всем командам плагина AdminUtils"
    children:
      adminutils.heal: true
      adminutils.god: true
